name: bact_phylogeny
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - prokka=1.14.6
  - roary=3.13.0
  - mafft=7.505
  - fasttree=2.1.11
  - iqtree=2.2.0
  - biopython=1.79
  - pandas=1.4.0
  - numpy=1.21.5
  - click=8.0.4
  - perl=5.32.1
  - perl-file-find-rule
  - perl-file-slurp
  - perl-lwp-simple
  - parallel
  - pip
